### ISSUE TITLE
prediction of remaining time

### ISSUE THREAD

**Issue by nevrome** [kforner/rcpp_progress#11]
Is it possible to implement a prediction of the time a loop monitored by rcpp_progress will take to finish? Maybe a simple extrapolation of the time needed so far? 

I would love to have that feature!

**Comment by kforner** [comment]
I really don't have time to develop the package. But I'll accept a PR if you're willing to do it.

**Comment by nevrome** [comment]
Would you mind taking a short look at my implementation over [here](https://github.com/nevrome/rcpp_progress)? I'm still pretty much a beginner concerning C++, so please tell me if it's indefensibly and unfixably shitty. Otherwise I would polish it a bit more and prepare a pull request. 

You can test my implementation by calling your test functions with `mode = 2`.
```
test_sequential(mode = 2)
test_multithreaded(mode = 2)
```

**Comment by kforner** [comment]
HI,
Running in a docker, I get this display:
> RcppProgress:::test_sequential(mode = 2)
0% 10%
|----|
*****| ⌛ 8s (1s)
*****| ⌛ 8s (2s)
*****| ⌛ 4s (2s)
*****| ⌛ 4s (3s)
*****| ⌛ 3s (3s)
*****| ⌛ 2s (4s)
*****| ⌛ 2s (5s)
*****| ⌛ 1s (5s)
*****| ⌛ 0s (6s)
*****|
> RcppProgress:::test_multithreaded(mode = 2)
0% 10%
|----|
*****| ⌛ 0s (0s)
*****| ⌛ 4s (1s)
*****| ⌛ 2s (1s)
*****| ⌛ 3s (2s)
*****| ⌛ 3s (3s)
*****| ⌛ 1s (3s)
*****| ⌛ 1s (4s)
*****| ⌛ 1s (5s)
*****| ⌛ 0s (5s)

To be compared with:

> RcppProgress:::test_multithreaded(mode = 1)
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**************************************************|


You should write an ETA class that

- stored and update the time
 - compute the ETA
 - print it.

**Comment by nevrome** [comment]
This output is as intended by me (except for the missing unicode clock symbol). The printing of the eta is uncomfortable as I didn't find a way to overwrite previous output on the R console. That's why I selected this vertical progress view. 

Of course I can outsource some of the time code into an own class, but the output and the calculation will remain more or less like this. Is this what you have in mind? 

Thanks for the feedback.

**Comment by kforner** [comment]
On Thu, Oct 26, 2017 at 3:53 PM, Clemens Schmid <notifications@github.com>
wrote:

> This output is as intended by me (except for the missing unicode clock
> symbol). The printing of the eta is uncomfortable as I didn't find a way to
> overwrite previous output on the R console. That's why I selected this
> vertical progress view.
>
Hmm I understand.



> Of course I can outsource some of the time code into an own class, but the
> output and the calculation will remain more or less like this. Is this what
> you have in mind?
>
Yes and No. I'm not sure this visualization should go in RcppProgress as
is, but RcppProgress could be made more flexible so that adding your own
progressbar could be straightforward.

It would need:
 - an abstract class/interface for ProgressBar, with virtual methods:
    * display_progress_bar / init_display
    * update/ / update_display
    * end_display
 -  Progress() and InterruptableProgressMonitor() should take optionally a
ProgressBar instance as argument.
 - The actual ProgressBar class should be renamed SimpleProgressBar for
instance, and be used if no progress bar instance was passed as argument,

This way you could customize the display to your needs.

**Comment by nevrome** [comment]
That sounds like an interesting challenge. At the weekend I'll maybe have some time for further development. Again thanks for taking the time!

**Comment by nevrome** [comment]
@kforner Please have a look at the [changes I made](https://github.com/nevrome/rcpp_progress). I tried to implement everything you suggested.

**Comment by kforner** [comment]
For the record: 
RcppProgress now supports custom progress bars. @nevrome provided an example of implementation of an ETA progress bar, that is available here: https://github.com/kforner/rcpp_progress/tree/master/inst/examples/RcppProgressETA

**Comment by kforner** [comment]
@nevrome have you tried using "\r" with Reprintf() to overwrite the output (for your ETA bar) ? 
I kind of remember I had problems but don't really remember the details.

**Comment by nevrome** [comment]
Oh - I understand. \r should cause a carriage return which is a jump to the start of the line and the next output could just overwrite the already written text. I tested it but it doesn't seem to have any effect at all.

**Comment by nevrome** [comment]
I asked for a solution on [stackoverflow](https://stackoverflow.com/questions/47623478/creating-a-progress-update-by-replacing-output-in-the-r-console-from-c-c) and I got one that works fine on unix-alike systems.

**Comment by kforner** [comment]
Could you test it with Reprintf() (i.e. on stderr) ?

**Comment by coatless** [comment]
@kforner it works with `REprintf()` 

![Progress update](https://media.giphy.com/media/l3mZbXvZfDjjzQl0Y/giphy.gif)

**Comment by kforner** [comment]
@coatless thanks.
