### ISSUE TITLE
Remove dependence on devtools

### ISSUE THREAD

**Issue by mlysy** [kforner/rcpp_progress#18]
The `testthat` unit tests use the `devtools::load_all` function in order to make the contents of packages in `inst/examples` available to the testing suite.  However, `devtools` itself depends on `curl`, which on unix systems requires a [separate installation of libcurl](https://github.com/jeroen/curl#installation).  This is fine if you have root access, but otherwise no `curl`, so no `devtools`, so no `RcppProgress`.

I've looked at your unit tests and I believe they can be rewritten without the use of `devtools::load_all`:

1.  Most tests can be combined into single cpp files, which in turn can be compiled on-the-fly with `Rcpp::sourceCpp`.
2.  The test in `inst/examples/RcppProgressExample` checks for multiple definitions in two cpp's.  Since `Rcpp::sourceCpp` is not intended for compiling multi-file projects, I suggest to put these test files in `src` and thus have them compiled with `RcppProgress` itself.

If you're OK with the suggestion I'm happy to get started on a pull request.

**Comment by kforner** [comment]
Hi mlysy

- devtools is in my opinion an essential package, so I'm not sure of the usefulness to try to avoid using it
- I use packages for the tests for the purpose of providing complete examples for users. So the point is to use a package for the tests. This way not only I test my package, but I also test the example packages. 

For a user, if you do not have devtools, why do you need to run the tests ?

If you want to get rid of devtools, you could write code that simulate devtools::load_all: that copies the test packages sources in temp location, install them also in a temp location, and load them.

Anyway thanks for your interest.

**Comment by mlysy** [comment]
Hi, kforner,

Apologies for the slow response...

I also use devtools whenever building packages.  However, I can't use it on the servers at work because devtools requires root access to install.  Perhaps the problem is too narrow to me, i.e., I should just petition the server admin to install curl, or patch a fork of your package.  I certainly understand your desire to provide unit tests on things (i.e., packages) in a way that mimics the end-user's experience.

That being said, would you agree that devtools is not essential to the *functionality* of your package, but rather only to the unit tests?  In other words, shouldn't someone be able to `#include <RcppProgress.h>` without actually needing devtools to be installed?

If so, perhaps you might consider moving devtools from the `Imports` field in the `DESCRIPTION` to `Suggests`, as described [here](http://r-pkgs.had.co.nz/description.html).  The benefit is that suggested packages aren't mandatory to install, whereas imported ones are.  Thus, a user who simply wishes to use your progress bar won't need devtools, whereas one who wishes to run the unit tests will.

Please let me know if you'd consider this weaker form of devtools requirement.  If so, I'm happy to go ahead with the pull request (I'd also add some simple error messages for tests run without devtools installed, as in the link above).

In case you're wondering why I'm so eager to get this done, I'm very happily using your progress bar in my [msde](https://CRAN.R-project.org/package=msde) package.  Computations are typically very long, so I'm constantly sending jobs to various servers across the country to which I don't have root access.

**Comment by kforner** [comment]
> If so, perhaps you might consider moving devtools from the Imports field in the DESCRIPTION to >Suggests, as described here. 

Certainly. Actually it is a mistake, I really thought it was a suggests. Go ahead if you want to do it, but I can also do it...

**Comment by mlysy** [comment]
I was in the zone so I went ahead and did it.
Also removed dependency on Rcpp and roxygen2 (latter included in devtools).  All tested on my machine with/without devtools installed.

**Comment by mlysy** [comment]
Seems I was a little quick on the draw with removing roxygen2, as its required by `load_all` but only suggested by devtools.  Travis CI OK now.

**Comment by kforner** [comment]
Hi, Just realized that I forgot to merge the pull request. I had to resubmit urgently because RcppProgress was removed from the CRAN. Anyway to facilitate the submission it was best to have as few changes as possible.

**Comment by kforner** [comment]
merged (but not yet submitted)
