### ISSUE TITLE
Is RcppProgress compatible with RcppParallel?

### ISSUE THREAD

**Issue by jlmelville** [kforner/rcpp_progress#21]
http://gallery.rcpp.org/articles/using-rcppprogress/ says that RcppProgress is compatible with multithreaded code, is there reason to believe it should work with RcppParallel? I realize this may turn out to be a question for RcppParallel, but thought I would ask here.

I had some success on Windows with the following skeleton:

```C++
struct MyWorker : public RcppParallel::Worker {
  Progress progress;
  tthread::mutex mutex;

  MyWorker(Progress& progress) : progress(progress) {  }

  void operator()(std::size_t begin, std::size_t end) {
    for (std::size_t i = begin; i < end; i++) {
      // real work here
      {
        tthread::lock_guard<tthread::mutex> guard(mutex);
        progress.increment();
        if (Progress::check_abort()) {
          return;
        }
      }
    } 
  }
};
```

but on Linux (admittedly only tried under a VM), I get messages along the lines of `Error: C stack usage  23365264492 is too close to the limit` if I increase the number of threads above 1, even with the simple parallel matrix square root example from: http://gallery.rcpp.org/articles/parallel-matrix-transform/

Is this approach doomed to failure?

**Comment by kforner** [comment]
Sorry I just realized that I completely missed this issue. Have you had any success ?

**Comment by jlmelville** [comment]
I have not. I am sure that attempting to call the R API (directly or indirectly) from inside a different thread is definitely doomed to failure. Perhaps <https://github.com/tnagler/RcppThread> (which advertised a thread-safe `Rcout`) could help here, but I haven't looked into this further.

Also, thank you for the work on this package @kforner!
