### ISSUE TITLE
all R functions described in the doc are missing

### ISSUE THREAD

**Issue by kforner** [kforner/rcpp_progress#25]
e.g. RcppProgress:::test_sequential

**Comment by bitbacchus** [comment]
Indeed. I was looking for RcppProgress:::CxxFlags(). Are there plans to (re-) add the R functions?

**Comment by kforner** [comment]
just need the time :( 
I welcome any contribution

**Comment by bitbacchus** [comment]
Thanks for your quick response @kforner 

Can you give me a hint where and why they went missing? I'd have a look then.

Right now the Reference manual on CRAN refers at least to `CxxFlags()`, while it's missing in the CRAN version.

**Comment by kforner** [comment]
It seems that the last commit that contained these is: https://github.com/kforner/rcpp_progress/tree/d9f04c68387ca85dc04d36adfe3c355c25cac578/R
I don't remember exactly why I removed them. I probably forgot that they were mentioned by the doc.

**Comment by bitbacchus** [comment]
Dear @kforner 

this seems to work. Before my PR, I'm thinking about changing some minor things:

- export the `test_*` functions to the package namespace
- use Roxygen to manage the namespace
- add an RStudio `.Rproj` file and an `.Rbuildignore` file to the repo

Would you be happy with these? This would just be a convenience for me, but I have no strong opinion if you don't like it.

Best,
Sebastian

**Comment by kforner** [comment]
good

> use Roxygen to manage the namespace

I think this is overkill, add a dependency and an extra step for building it. (but I like roxygen ;) )

> .Rbuildignore file to the repo

ok

> .Rproj

This is personal and should not be part of the project. For example I do not use rstudio.

**Comment by bitbacchus** [comment]
> > use Roxygen to manage the namespace
> 
> I think this is overkill, add a dependency and an extra step for building it. (but I like roxygen ;) )

Roxygen is just used to generate the NAMESPACE file and the documentation, of course. There is no need to have Roxygen as a dependency. Its no effort at all, I'll just do it and you can decide on this part later.

> > .Rbuildignore file to the repo
> 
> ok
> 
> > .Rproj
> 
> This is personal and should not be part of the project. For example I do not use rstudio.

agree.

**Comment by kforner** [comment]
fixed by #32
