### ISSUE TITLE
Progress bar mimicking "progress" package

### ISSUE THREAD

**Issue by pcarbo** [kforner/rcpp_progress#26]
Thank you for providing this useful package. We have been using it to develop a new package (see [here](https://github.com/stephenslab/fastTopics)) and so far it is working very well.

I have a feature request of sorts. I'm wondering if it would be possible to provide an example class (inheriting from `ProgressBar`) that mimics the display of the default progress bar provided by the [progress package](https://github.com/r-lib/progress). e.g.,

```
[======================================================>----------------]  77%
```

Or perhaps this already exists somewhere?

**Comment by kforner** [comment]
Hi. 
Glad you find this package useful!
Do you want to have a try and make a pull request ?

**Comment by pcarbo** [comment]
I'll do my best. Do you happen to know of a package that is doing this already, or doing something similar (so I could build on their code)?
