### ISSUE TITLE
installed package rcpt_progress not ... available

### ISSUE THREAD

**Issue by eallman** [kforner/rcpp_progress#29]
I suspect I am doing something silly, but I installed RcppProgress on R 4.2.1. and tried to run the test

> library("RcppProgress")
> RcppProgress:::test_sequential(max, nb, display_progress)
Error: object 'test_sequential' not found

Similarly,
test_sequential <- function(max=100, nb=1000, display_progress=TRUE) {
        .Call("test_sequential_wrapper2", max, nb, display_progress, PACKAGE = "RcppProgressExample")
        invisible()
}

did not work.

It seems I have failed in installing the package, using  install.packages("RcppProgress").  

When I look in 

/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include

the header files, for example, are missing.

I am trying to put a progress bar into some cpp code.  Thank you for any help you can give me.

Elizabeth

**Comment by kforner** [comment]
The documentation is outdated. Look at the readme for some test examples: https://github.com/kforner/rcpp_progress/blob/master/README.md
The examples are in https://github.com/kforner/rcpp_progress/tree/master/inst/examples

Feel free to update the documentation...

Also, I don't know on Mac, but on linux, when you install it using e.g. `install.packages`, you got that kind of layout:

```
$ ll /usr/local/lib/R/site-library/RcppProgress/
total 36
drwxrwxr-x 7 root staff 4096 Mar 30 16:41 ./
drwxrwsr-x 1 root staff 4096 Mar 30 16:41 ../
-rw-rw-r-- 1 root staff  875 Mar 30 16:41 DESCRIPTION
-rw-rw-r-- 1 root staff  120 Mar 30 16:41 INDEX
drwxrwxr-x 2 root staff 4096 Mar 30 16:41 Meta/
-rw-rw-r-- 1 root staff    0 Mar 30 16:41 NAMESPACE
drwxrwxr-x 5 root staff 4096 Mar 30 16:41 examples/
drwxrwxr-x 2 root staff 4096 Mar 30 16:41 help/
drwxrwxr-x 2 root staff 4096 Mar 30 16:41 html/
drwxrwxr-x 2 root staff 4096 Mar 30 16:41 include/
```

```
$ ll /usr/local/lib/R/site-library/RcppProgress/include/
total 32
drwxrwxr-x 2 root staff 4096 Mar 30 16:41 ./
drwxrwxr-x 7 root staff 4096 Mar 30 16:41 ../
-rw-rw-r-- 1 root staff 4762 Mar 30 16:41 interruptable_progress_monitor.hpp
-rw-rw-r-- 1 root staff 1113 Mar 30 16:41 interrupts.hpp
-rw-rw-r-- 1 root staff 2768 Mar 30 16:41 progress.hpp
-rw-rw-r-- 1 root staff  655 Mar 30 16:41 progress_bar.hpp
-rw-rw-r-- 1 root staff 2230 Mar 30 16:41 simple_progress_bar.hpp
```

**Comment by eallman** [comment]
Thanks.  I will look at your suggestions.

I have a slight update.  I have been installing the package from within Rstudio.  Just now I copied the .hpp files into the right location and got R project to compile at least (no progress bar yet).  I will keep trying things.  Thank you!  particularly for the quick response.

Last night it took 12 hours to run a loop in Cpp.  I'd definitely like to keep track of how long the computations will take.  It's a great service your package offers.

Best wishes.

Elizabeth
