### ISSUE TITLE
abort()

### ISSUE THREAD

**Issue by elbamos** [kforner/rcpp_progress#5]
I'm seeing warnings from R-devel with my package that R:
```
Found ‘abort’, possibly from ‘abort’ (C)
```
in two objects. The two objects don't call `stop` or `abort` or any of that, but they do use `RcppProgress`, which has a function called `abort()`.  Is it possible the new warning is related to `RcppProgress`?

Thanks.

**Comment by kforner** [comment]
> Is it possible the new warning is related to RcppProgress?

Probably yes. It seems to be a false positive, but to the fact that my function is called abort, like the stdlib function. I should probably rename it. I'd accept a pull request...

**Comment by elbamos** [comment]
I'd submit a PR, but any submission at this point is also going to have to change the tests to handle CRAN's new rule about R_registerDynamic, or whatever it is.  (Discussion on the Rcpp main issues board.)  I don't really feel like I understand that issue - my own solution for my package feels like a kludge.

**Comment by kforner** [comment]
Do you still see this ? I suppose not since RcppProgress does not use a shared library anymore....

**Comment by kforner** [comment]
I'm closing the issue. Please reopen it if you're still seeing warnings.
