### ISSUE TITLE
Warnings on compilation when not using OpenMP

### ISSUE THREAD

**Issue by twolodzko** [kforner/rcpp_progress#6]
I added

```c++
// [[Rcpp::depends(RcppProgress)]]
#include <progress.hpp>
#include <progress_bar.hpp>
```
to my code, and now I warnings during compilation:

```c++
C:/---------/R/win-library/3.4/RcppProgress/include/interruptable_progress_monitor.hpp:101:0: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
 #pragma omp critical
 ^
C:/---------/R/win-library/3.4/RcppProgress/include/interruptable_progress_monitor.hpp:143:0: warning: ignoring #pragma omp atomic [-Wunknown-pragmas]
 #pragma omp atomic
 ^
C:/---------/R/win-library/3.4/RcppProgress/include/interruptable_progress_monitor.hpp:149:0: warning: ignoring #pragma omp critical [-Wunknown-pragmas]
 #pragma omp critical
```

**Comment by kforner** [comment]
what do you mean by not using OpenMP ? How do you disable it ?

**Comment by twolodzko** [comment]
@kforner  Sorry: I mean using raw Rcpp code, without any references to omp.

**Comment by kforner** [comment]
Ok. So I suppose you're using a C++ compiler that does not support OpenMP, probably in windows ?

**Comment by twolodzko** [comment]
@kforner yes

```
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language EN                          
 collate  Polish_Poland.1250          
 tz       Europe/Warsaw               
 date     2017-09-08                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version date       source                                 
 clisymbols     1.2.0   2017-06-19 Github (gaborcsardi/clisymbols@e49b4f5)
 MASS         * 7.3-47  2017-02-26 CRAN (R 3.4.1)                         
 Rcpp         * 0.12.12 2017-07-15 CRAN (R 3.4.1)                         
 RcppProgress   0.3     2017-01-05 CRAN (R 3.4.1)                         
 sessioninfo    1.0.1   2017-09-08 Github (r-lib/sessioninfo@e813de4)     
 withr          2.0.0   2017-07-28 CRAN (R 3.4.1) 
```

**Comment by kforner** [comment]
seen here: http://www.ipd.uni-karlsruhe.de/multicore/research/download/HowToGuide-OpenMP.pdf
look in 1.2 Windows to install a Mingw with openMP support.

**Comment by twolodzko** [comment]
@kforner do you mean that omp is needed for RcppProgress to work and not throw warnings? I do not need it to run my code, the issue is that after adding RcppProgress to my code, it started throwing warnings when compiling.

**Comment by kforner** [comment]
> do you mean that omp is needed for RcppProgress to work and not throw warnings?

good question. I guess that you can either accept the warnings, or maybe there is a compiler flag to ignore those warnings, that you could put in MakeVars. 
I remember that at the beginning I checked it without OpenMP, but I don't remember anything about warnings. 

seems related to this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66943

A work-around would be to wrap each #pragma omp with a #ifdef _OPENMP. 
I'd accept a pull request if you want to do it.

**Comment by twolodzko** [comment]
@kforner FYI: it is done, I just tested on Windows machine and it throws no warnings. Please check the PR to be sure if this is what you meant.

**Comment by kforner** [comment]
Thanks for the PR.
